TAXONOMY = {
    "AI & Machine Learning": {
        "Speech & Audio AI": [],
        "MLOps & Model Serving": [],
        "AI Data & Training Infrastructure": [],
        "AI Model Development Platforms": [],
        "General Purpose AI Models": [],
        "AI World Models": [],
        "AI Compute & Cloud Infrastructure": [],
        "AI Agent Platforms And Automation": [],
        "AI Agent Memory & State": [],
        "Uncategorized": [],
    },
    "Cybersecurity": {
        "IAM / PAM": [],
        "Endpoint Security": [],
        "Network Security": [],
        "Cloud Security": [],
        "AppSec / DevSecOps": [],
        "SOC & Incident Response": [],
        "AI Model Safety": [],
        "External Attack Surface Management": [],
        "Vendor Risk Management": [],
        "Secrets And Non Human Identity Security": [],
        "Threat Detection & Intelligence": [],
        "AI Security And Guardrails": [
            "AI Agent & Non-Human Identity Security",
            "AI Governance & Compliance",
            "AI Red-Teaming & Model Evaluation",
        ],
        "Cybersecurity Risk Management": [],
        "Identity Verification And Onboarding": [],
        "Cryptographic Data Verification": [],
        "Data Security & Privacy": [],
        "Device & Firmware Security": [],
        "Biometric & Deepfake Protection": [],
        "Physical Security Intelligence": [],
        "Uncategorized": [],
    },
    "Enterprise Software": {
        "CRM & Sales": [],
        "ERP & Business Operations": [],
        "ERP Modernization & Migration": [],
        "Field & Industrial Operations": [],
        "Internal Audit Automation": [],
        "Customer Support": [],
        "Enterprise Project Management": [],
        "Productivity Tools": [
            "AI Email & Communication Assistants",
            "AI Meeting & Notes Assistants",
            "Team Knowledge Management",
            "AI Workflow Automation & Digital Workers",
        ],
        "Supply Chain & Logistics Automation": [],
        "Uncategorized": [],
    },
    "FinTech": {
        "WealthTech": [],
        "Investment Intelligence": [],
        "Corporate Treasury Management": [],
        "Trading Infrastructure": [],
        "Embedded Financial Services": [],
        "Crypto Compliance Solutions": [],
        "Financial Planning Analytics": [],
        "Digital Asset Liquidity": [],
        "Financial Compliance Automation": [],
        "Tax Compliance Automation": [],
        "Payment And Fraud Solutions": [],
        "Mortgage And Lending Tech": [],
        "Uncategorized": [],
    },
    "HealthTech": {
        "Mental Health": [],
        "Personal Health Insights": [],
        "Digital Health Insurance": [],
        "Medical Weight Management": [],
        "Pharma Regulatory Compliance": [],
        "AI Foundation Models For Biology": [],
        "Computational Immune Engineering": [],
        "Regulatory Submission Automation": [],
        "Clinical Trial Optimization": [],
        "AI Chronic Care Management": [],
        "Health Insurance Platforms": [],
        "Medical Practice Software": [],
        "Immune System Analytics": [],
        "Cancer Precision Therapeutics": [],
        "Male Reproductive Health": [],
        "Neural Interface Technologies": [],
        "AI Oncology Diagnostics": [],
        "Medical Imaging AI": [],
        "Healthcare Practice Management": [],
        "AI Orthodontic Imaging": [],
        "AI Ambient Clinical Assistants": [],
        "AI Fertility Treatment Optimization": [],
        "Provider Credentialing Automation": [],
        "Specialty Practice Workflow Automation": [],
        "Medical Devices & Interventional Technology": [],
        "Diagnostics & Testing": [],
        "Uncategorized": [],
    },
    "Life Sciences": {
        "AI For Market Access": [],
        "AI For Material Discovery": [],
        "AI For Drug Discovery": [],
        "AI For Material Science": [],
        "Federated AI For Life Sciences": [],
        "AI Clinical Trial Optimization": [],
        "AI Precision Oncology Diagnostics": [],
        "AI Neuroscience Research": [],
        "AI Driven Bioproduction": [],
        "AI For Patent Intelligence": [],
        "Advanced Microscopy Diagnostics": [],
        "AI Medical Workflow": [],
        "AI Material Science Simulation": [],
        "Therapeutics & Drug Development": [],
        "Uncategorized": [],
    },
    "Developer Tools & Infrastructure": {
        "CI/CD & DevOps": [],
        "Observability & Monitoring": [],
        "Low-Code / No-Code": [],
        "API Infrastructure": [],
        "Search Infrastructure": [],
        "AI Driven Developer Productivity": [
            "AI Code Review",
            "AI Documentation Generation",
            "AI Test Generation",
            "AI Codebase Understanding & Search",
            "Engineering Analytics & Planning",
        ],
        "Infrastructure Monitoring": [],
        "AI Code Generation And Repair": [],
        "Uncategorized": [],
    },
    "Robotics": {
        "Industrial Robotics": [],
        "Robot Foundation Models": [],
        "General Purpose Robotics": [],
        "Industrial Automation Robotics": [],
        "Logistics And Warehouse Robotics": [],
        "Biomimetic Surveillance Drones": [],
        "Autonomous Industrial Robotics": [],
        "Industrial Asset Inspection": [],
        "Uncategorized": [],
    },
    "CleanTech": {
        "AI Weather And Climate": [],
        "Textile Waste Recycling": [],
        "Solar Water Purification": [],
        "Renewable Energy Forecasting": [],
        "Energy Storage Systems": [],
        "Enzyme Based Recycling": [],
        "Pollution Control Technology": [],
        "Sustainable Metal Recovery": [],
        "Decarbonized Industrial Heat": [],
        "Transport Emissions Capture": [],
        "Urban Heat Solutions": [],
        "Sustainable Biomanufacturing": [],
        "Circular Appliance Solutions": [],
        "E Waste Metal Recovery": [],
        "Industrial Byproduct Upcycling": [],
        "Demand Response Management": [],
        "Water Efficiency Solutions": [],
        "Grid Resilience Technology": [],
        "Uncategorized": [],
    },
    "EdTech": {
        "K-12 Education": [],
        "Higher Education": [],
        "AI For Education And Creativity": [],
        "Uncategorized": [],
    },
    "E-commerce & Retail": {
        "D2C Brands": [],
        "Refurbished Electronics Marketplace": [],
        "AI Powered Commerce": [],
        "Visual Commerce Tools": [],
        "Restaurant Management": [],
        "Hospitality & Travel Operations": [],
        "Retail Commerce Automation": [],
        "AI Commerce Integration": [],
        "AI Native Ecommerce Platforms": [],
        "Uncategorized": [],
    },
    "Marketing Tech": {
        "SEO & Content": [],
        "Social Media": [],
        "Ad Tech": [],
        "Influencer Marketing": [],
        "Brand Safety And Marketing": [],
        "AI Lead Generation": [],
        "Outbound Sales Automation": [],
        "Web Data Intelligence": [],
        "Retail Intelligence": [],
        "Consumer Insights Automation": [],
        "Video Ad Automation": [],
        "Automated Marketing Assets": [],
        "Personalized Media Experiences": [],
        "Uncategorized": [],
    },
    "Quantum Computing": {
        "Quantum Processors & Systems": [],
        "Uncategorized": [],
    },
    "Aerospace & Defense": {
        "Aviation And Flight Systems": [],
        "AI Aerospace Defense Simulation": [],
        "Aerospace Defense": [],
        "Drone Defense Systems": [],
        "Defense And Security Robotics": [],
        "Military And Defense Automation": [],
        "Aviation Operational Intelligence": [],
        "Uncategorized": [],
    },
    "Energy": {
        "Energy Efficiency Software": [],
        "Nuclear Energy": [],
        "AI Energy Infrastructure": [],
        "AI Industrial Operations": [],
        "Uncategorized": [],
    },
    "Mobility": {
        "Urban Mobility Solutions": [],
        "Electric Cargo Mobility": [],
        "EV Charging Networks": [],
        "Uncategorized": [],
    },
    "SpaceTech": {
        "Space Based Energy": [],
        "Dedicated Small Satellite Launch": [],
        "Space Based Data Services": [],
        "Mars Surface Exploration": [],
        "Reusable Space Vehicles": [],
        "In Space Mobility": [],
        "Launch And Propulsion Systems": [],
        "Uncategorized": [],
    },
    "HRTech": {
        "HR Management Platforms": [],
        "Recruiting And Talent Acquisition": [],
        "Workforce Compliance Platforms": [],
        "Gig Economy Platforms": [],
        "Corporate Learning": [],
        "Uncategorized": [],
    },
    "InsurTech": {
        "Insurance Claims Automation": [],
        "Insurance Backoffice Automation": [],
        "Wholesale Insurance Marketplace": [],
        "Climate Risk Insurance": [],
        "Commercial Insurance Brokerage": [],
        "Specialty And Emerging Risk Insurance": [],
        "Uncategorized": [],
    },
    "LegalTech": {
        "Legal Compliance Automation": [],
        "AI Legal Practice Automation": [],
        "Regulatory Document Automation": [],
        "Audit And Risk Automation": [],
        "AI Risk Certification": [],
        "Policy Intelligence And News": [],
        "Product Compliance Management": [],
        "Uncategorized": [],
    },
    "PropTech": {
        "Construction Project Intelligence": [],
        "AI Engineering Design": [],
        "Real Estate Agent Software": [],
        "Uncategorized": [],
    },
    "Hardware": {
        "Precision Additive Manufacturing": [],
        "Consumer Electronics": [],
        "Semiconductor & Chips": [],
        "Sensors & IoT Devices": [],
        "Uncategorized": [],
    },
    "FoodTech": {
        "Sustainable Food Production & Ingredients": [],
        "Food Manufacturing & Quality Tech": [],
        "Personalized Nutrition & Wellness": [],
        "Food Supply Chain & Traceability": [],
        "Uncategorized": [],
    },
    "AgriTech": {
        "Farm Operations & Precision Agriculture": [],
        "Agricultural Finance & Commodity Markets": [],
        "Agricultural Biosecurity & Wildlife Management": [],
        "Uncategorized": [],
    },
    "MediaTech": {
        "AI Media Management": [],
        "Generative Media Tools": [],
        "Digital Experience Development": [],
        "Digital Experience Design": [],
        "AI Content Production": [],
        "Uncategorized": [],
    },
    "Consumer Tech": {
        "Gaming & Entertainment": [],
        "Personal Productivity": [],
        "Social & Community": [],
        "Lifestyle & Wellness": [],
        "Accessibility & Inclusion": [],
        "Uncategorized": [],
    },
    "PetTech": {
        "Pet Insurance": [],
        "Veterinary Tech": [],
        "Pet Nutrition & Wellness": [],
        "Pet Training & Behavior": [],
        "Pet Monitoring & Connected Devices": [],
        "Uncategorized": [],
    },
    "Uncategorized": {},
}

HORIZONTAL_SUBSECTORS = {
    "AI Agent Platforms And Automation",
    "General Purpose AI Models",
    "AI World Models",
    "Speech & Audio AI",
}


def validate_subsectors(subsectors: list[str], sectors: list[str] = []) -> list[str]:
    if sectors and set(sectors) <= {"AI & Machine Learning", "Developer Tools & Infrastructure"}:
        return subsectors
    has_vertical = any(
        s not in HORIZONTAL_SUBSECTORS and s != "Uncategorized"
        for s in subsectors
    )
    if not has_vertical:
        return subsectors

    removed = [s for s in subsectors if s in HORIZONTAL_SUBSECTORS]
    if removed:
        print(f"[validate_subsectors] Removed horizontal tags (vertical context detected): {removed}")
    return [s for s in subsectors if s not in HORIZONTAL_SUBSECTORS]


# Subsectors that already capture the company's actual product more precisely
# than the generic ERP tag — if one of these is present alongside "ERP & Business
# Operations", the company is a point solution or an ERP-adjacent layer, not the
# ERP itself, even when the LLM keeps both despite the definition's NOT clauses.
ERP_REDIRECT_SUBSECTORS = {
    "Supply Chain & Logistics Automation",
    "ERP Modernization & Migration",
    "Productivity Tools",
}


def demote_generic_erp_tag(subsectors: list[str]) -> list[str]:
    if "ERP & Business Operations" not in subsectors:
        return subsectors
    if not (set(subsectors) & ERP_REDIRECT_SUBSECTORS):
        return subsectors
    print("[demote_generic_erp_tag] Dropped ERP & Business Operations (more specific subsector present)")
    return [s for s in subsectors if s != "ERP & Business Operations"]


def remove_redundant_uncategorized(subsectors: list[str]) -> list[str]:
    """Drop the 'Uncategorized' tag when real subsectors are also present.
    Coexistence of 'Uncategorized' with actual subsector tags is a logical
    contradiction: if a real subsector was found, the item is not
    uncategorized.
    """
    if len(subsectors) <= 1:
        return subsectors
    if "Uncategorized" not in subsectors:
        return subsectors
    print("[remove_redundant_uncategorized] Dropped redundant 'Uncategorized' tag (real subsector present)")
    return [s for s in subsectors if s != "Uncategorized"]


SUBSECTOR_DEFINITIONS = {
    # AI & Machine Learning
    "Speech & Audio AI": "Speech and audio technology sold as the product itself — TTS, STT, speaker diarization, voice cloning, audio enhancement models and APIs. NOT vertical applications delivering outcomes through voice (AI phone assistants, meeting note-takers, contact center automation).",
    "MLOps & Model Serving": "Tools for deploying, monitoring, and serving AI models in production. Includes model serving infrastructure, experiment tracking, model registries, performance monitoring, and A/B testing for models. NOT data pipelines, NOT model training platforms.",
    "AI Data & Training Infrastructure": "Infrastructure for collecting, processing, labeling, and preparing data for AI training. Includes synthetic data generation, data labeling platforms, feature stores, and fine-tuning infrastructure. NOT model serving, NOT MLOps tooling.",
    "AI Model Development Platforms": "Platforms for building, training, fine-tuning, and optimizing general-purpose AI models including edge deployment. Includes foundation model infrastructure, synthetic data, reinforcement learning. NOT AI models or platforms built for a specific scientific/domain vertical that already has its own home — drug discovery, protein/antibody engineering, and biomanufacturing (use AI For Drug Discovery or AI Driven Bioproduction), materials discovery and material science modeling (use AI For Material Discovery or AI For Material Science) — even though the underlying technique is also 'building and training AI models,' the product IS a vertical scientific tool, not a general-purpose model-development platform. NOT a company whose product IS the foundation model itself, with no separate tooling/platform layer being sold (use General Purpose AI Models instead — e.g. Mistral AI, DeepSeek). NOT AI-powered end-user applications that merely use models internally without offering model-building, training, or fine-tuning tooling to others — a code editor with AI features is AI Code Generation And Repair, a no-code game-creation tool is Low-Code / No-Code or its specific product category, not this. The defining trait is being infrastructure/tooling FOR BUILDING models, not simply being powered by AI.",
    "General Purpose AI Models": "Foundation models and general-purpose LLMs. The product IS the model itself — not a vertical application built on top of it.",
    "AI World Models": "AI systems that build internal representations of the physical world for prediction and planning. Used in robotics, autonomous systems, and simulation.",
    "AI Agent Platforms And Automation": "STRICT DEFINITION. Developer-facing infrastructure and frameworks for building, deploying, and orchestrating autonomous AI agents. The PRIMARY customer is a developer or technical team building their OWN agents — not a business user receiving an agent as a service. Includes agent runtimes, multi-agent orchestration frameworks, agent memory layers, and sandboxed execution environments. NOT vertical AI applications that happen to use agents internally (those go in their specific vertical sector). NOT automation tools for non-technical business users. NOT AI assistants or digital workers sold as a finished product to end users. Examples: LangChain, CrewAI, xmemory. NOT examples: 11x AI, Parloa, Cogna, Twin.",
    "AI Agent Memory & State": "Infrastructure providing persistent memory, state management, and context storage for AI agents and LLM applications. Includes memory layers, vector stores for agent context, and structured state management systems. NOT general vector databases, NOT MLOps tooling.",
    # Robotics
    "Industrial Robotics": "Physical robotic arms and machines for fixed manufacturing tasks (welding, assembly, painting).",
    "Robot Foundation Models": "AI models and software infrastructure for training and running robots. No physical product.",
    "General Purpose Robotics": "Physical robots designed to perform multiple tasks across different environments.",
    "Industrial Automation Robotics": "Robotic systems that automate specific industrial processes (construction, agriculture, inspection).",
    "Logistics And Warehouse Robotics": "Autonomous robots for warehouse operations, picking, sorting, and last-mile delivery.",
    "Biomimetic Surveillance Drones": "Drones that mimic living organisms for surveillance and defense purposes.",
    "Autonomous Industrial Robotics": "Fully autonomous robotic systems for heavy industry (earthworks, mining, large-scale construction).",
    "Industrial Asset Inspection": "Robots and drones used to inspect physical infrastructure (pipelines, bridges, facilities).",
    # Cybersecurity
    "IAM / PAM": "Identity and access management, privileged access control. Who can access what. NOT payment/transaction authorization or spend governance for AI agents (use Payment And Fraud Solutions or Embedded Financial Services), even if it involves verifying agent identity.",
    "Endpoint Security": "Protection of devices (laptops, servers, mobile). EDR, antivirus, workstation security.",
    "Network Security": "Protection of network infrastructure, traffic monitoring, firewall, zero trust networking.",
    "Cloud Security": "Security for cloud infrastructure, workloads, and data. CSPM, CWPP, cloud-native security.",
    "AppSec / DevSecOps": "Security integrated into the software development lifecycle. SAST, DAST, code scanning.",
    "SOC & Incident Response": "Security operations center tools, incident detection, response automation.",
    "AI Model Safety": "Protecting AI models from attacks, adversarial inputs, and misuse. NOT general AI security.",
    "External Attack Surface Management": "Discovering and monitoring externally exposed assets and vulnerabilities.",
    "Vendor Risk Management": "Assessing and monitoring third-party and supply chain security risks.",
    "Secrets And Non Human Identity Security": "Managing API keys, tokens, certificates, and machine identities.",
    "Threat Detection & Intelligence": "Real-time threat detection and threat intelligence feeds.",
    "AI Security And Guardrails": "STRICT DEFINITION. Products whose PRIMARY function is securing AI systems, models, or autonomous agents themselves — discovering and governing AI/agent usage, enforcing runtime guardrails, protecting against prompt injection and agent hijacking, and privacy-preserving AI computation. NOT general cybersecurity or cloud security platforms where AI is one feature among others (use Cloud Security, External Attack Surface Management, SOC & Incident Response). NOT AppSec/DevSecOps tools securing code or the SDLC, even if AI-assisted (use AppSec / DevSecOps). NOT security awareness or phishing simulation training (use Cybersecurity Risk Management). NOT content moderation or trust & safety for consumer platforms, NOT AI model hosting/access platforms (neither belongs in Cybersecurity at all). Examples: Astrix Security, CodeIntegrity, Lakera, Neo Security. NOT examples: Tenable, BoostSecurity, Bodyguard.ai, Arsen.",
    "Cybersecurity Risk Management": "GRC, risk scoring, compliance frameworks, security awareness training.",
    "Identity Verification And Onboarding": "Verifying user identities during onboarding. KYC, biometric verification, fraud prevention.",
    "Cryptographic Data Verification": "Cryptographic proofs, digital signatures, on-chain data integrity.",
    "Data Security & Privacy": "Data protection, encryption, masking, and privacy compliance.",
    "Device & Firmware Security": "Security for IoT devices, embedded systems, and firmware.",
    "Biometric & Deepfake Protection": "Detecting manipulated biometric data, deepfakes, and synthetic identities.",
    "Physical Security Intelligence": "AI-powered physical security, surveillance, and threat detection in the real world.",
    # Enterprise Software
    "CRM & Sales": "Software for managing customer relationships, sales pipelines, and revenue operations. Direct sales tooling for B2B teams. NOT inbound voice/chat agents whose primary function is answering customer calls, chats, or support requests, even when they also qualify leads or book appointments as a secondary function — those belong under Customer Support instead, since the product IS a call/chat handling layer, not a CRM or sales-pipeline tool.",
    "ERP & Business Operations": "Core enterprise resource planning software that IS the system of record across multiple business functions — finance, inventory, manufacturing, procurement, and supply chain at an organizational level. Includes SAP, Oracle-like platforms and their modern equivalents, AND industry-specific full ERP systems for a single vertical (e.g. manufacturing ERP, telecom OSS/BSS) where customers store and manage their core operational data day to day. Litmus test: if the company were to shut down, would customers lose their primary system of record? If yes, and it spans multiple business functions, it belongs here. NOT a company whose own description says it 'integrates with', 'connects to', 'syncs with', or 'sits on top of' an existing ERP — that phrasing means a third-party ERP is already the system of record and this product is a layer around it (use ERP Modernization & Migration if the layer's job is migrating/modernizing/orchestrating that ERP, or the specific point-solution subsector otherwise, e.g. Supply Chain & Logistics Automation for procurement/inventory/sourcing tools, Corporate Treasury Management or Financial Compliance Automation for reconciliation/spend/expense tools). NOT single-function point solutions covering only one process (procurement, expense, reconciliation, inventory, travel, tax) even if that process is finance- or ops-adjacent — those belong in their specific subsector. NOT generic small-business tools without vertical-specific depth (e.g. a generic 'manage sales, inventory, invoicing' SMB app with no named vertical). NOT frontline/plant-floor monitoring or predictive-maintenance co-pilots connected to machines/cameras without being the system of record (use Field & Industrial Operations). NOT single-vertical revenue-management or pricing point solutions for hospitality/travel operators (use Hospitality & Travel Operations).",
    "ERP Modernization & Migration": "AI-powered tools and agents that migrate, modernize, upgrade, or orchestrate a customer's EXISTING third-party ERP (e.g. SAP, Oracle, NetSuite) — automating tasks like S/4HANA migration, fit-gap analysis, data harmonization, code remediation, system health assessments, or executing specific workflows (order-to-cash, procure-to-pay, RFQ, order processing) by connecting into that ERP via API/integration. The customer already runs someone else's ERP as their system of record; this product is bought by IT/transformation teams or embedded operations teams to accelerate a migration project or automate a slice of ERP-adjacent workflow, not to replace the ERP itself. NOT the ERP itself (use ERP & Business Operations), NOT generic IT observability/DevOps tooling unrelated to ERP systems specifically.",
    "Field & Industrial Operations": "Software and AI platforms automating frontline and field operations for industrial sectors — utilities, water, gas, energy, construction, facilities management, and field services. Includes workforce management, site intelligence, compliance tracking, workplace safety (EHS), and operational decision-making for field teams. NOT general ERP, NOT supply chain logistics.",
    "Internal Audit Automation": "Platforms automating internal audit workflows including evidence collection, control testing, and workpaper generation. Serves internal audit teams, compliance officers, and external auditors. NOT general compliance software, NOT risk management platforms, NOT legal document automation.",
    "Customer Support": "Tools for managing customer service, helpdesk, and support operations. Includes voice agents and conversational AI deployed for customer-facing support.",
    "Enterprise Project Management": "Horizontal tools for planning, tracking, and coordinating projects and teams across an organization. NOT vertical industry software.",
    "Productivity Tools": "STRICT DEFINITION. Horizontal tools that enhance individual or team productivity across ANY profession, with no single target vertical — email assistants, scheduling, note-taking, meeting assistants, knowledge management, and general-purpose AI agents that automate business workflows as a finished product (digital workers). NOT industry-specific tools, NOT CRM or ERP. NOT tools built for one specific vertical even if AI-powered — classify those by their vertical instead: real estate agents (use Real Estate Agent Software), medical/dental practices (use Medical Practice Software), insurance brokers (use Insurance Backoffice Automation), investors/VCs (use Investment Intelligence), in-house legal teams (use Legal Compliance Automation), accounting firms (use Financial Compliance Automation), government/public sector (use its matching sector). NOT AI model training/deployment infrastructure (use MLOps & Model Serving or AI Model Development Platforms), even if marketed as boosting productivity.",
    "Supply Chain & Logistics Automation": "Software automating supply chain, procurement, and commercial operations for B2B businesses. Includes order processing automation, quote and invoice management, freight brokerage, shipment tracking, carrier management, warehouse operations, and procurement workflows. NOT general ERP, NOT robotics, NOT horizontal workflow tools.",
    "AI Compute & Cloud Infrastructure": "Cloud platforms providing GPU instances, clusters, and compute infrastructure specifically for AI workloads. Includes GPU cloud providers, serverless inference platforms, and vertically-integrated AI compute solutions. NOT MLOps tooling, NOT model training platforms.",
    "Real Estate Agent Software": "Software platforms built specifically for real estate agents, brokers, and property managers. Includes AI assistants for inbox and pipeline management, virtual staging, CMA tools, listing marketing automation, and CRM built for real estate. NOT construction tech, NOT property analytics for investors, NOT generic CRM.",
    # FinTech
    "WealthTech": "Platforms for personal and institutional wealth management, portfolio tracking, and investment advisory. Includes robo-advisors and digital private banking. NOT trading execution infrastructure.",
    "Investment Intelligence": "Data and analytics platforms helping investors make decisions. Includes alternative data, market intelligence, and investment research tools. NOT trading execution, NOT portfolio management software.",
    "Corporate Treasury Management": "Software for managing corporate cash, liquidity, FX exposure, and short-term investments. NOT accounting or ERP.",
    "Trading Infrastructure": "Low-latency execution platforms, order management systems, and market connectivity for financial trading. NOT investment research or portfolio management.",
    "Embedded Financial Services": "APIs and infrastructure allowing non-financial businesses to embed payments, lending, or cards into their own products. Includes payment/spending infrastructure specifically built for AI agents to transact autonomously (wallets, virtual cards, spend delegation for agents).",
    "Crypto Compliance Solutions": "Tools for compliance, transaction monitoring, and regulatory reporting specific to crypto and digital assets. NOT general financial compliance.",
    "Financial Planning Analytics": "Software for budgeting, forecasting, and financial modeling used by CFO teams and financial planners. NOT general BI tools.",
    "Digital Asset Liquidity": "Platforms providing liquidity for crypto and digital assets. Includes market makers, DEX aggregators, and OTC desks. NOT compliance or custody.",
    "Financial Compliance Automation": "Automating regulatory compliance workflows in financial services. Includes AML, reporting, and audit trails. NOT crypto-specific compliance.",
    "Tax Compliance Automation": "Software automating tax filing, calculation, and reporting for individuals and businesses. NOT general financial compliance.",
    "Payment And Fraud Solutions": "Payment processing platforms and fraud detection tools. Includes payment orchestration, acquiring, real-time transaction fraud prevention, and governance/policy enforcement for AI-agent-initiated payments and transactions (spending limits, vendor allowlists, transaction audit trails for agents). NOT generic identity/access management for AI agents that doesn't specifically govern payments or spending (use IAM / PAM or Secrets And Non Human Identity Security).",
    "Mortgage And Lending Tech": "Platforms for mortgage origination, consumer and business lending, credit scoring, and loan lifecycle management. Includes document automation, borrower communication, underwriting tools, and BNPL infrastructure. NOT payment processing, NOT embedded finance APIs.",
    # HealthTech
    "Mental Health": "Digital platforms for mental health therapy, coaching, and wellness. Includes teletherapy, CBT apps, and employer mental health benefits.",
    "Personal Health Insights": "Consumer platforms collecting and analyzing personal health data to provide actionable insights. Includes wearable integrations and health dashboards. NOT clinical diagnostics.",
    "Digital Health Insurance": "Digitally-native health insurance plans sold directly to consumers or employers. NOT insurance backoffice tools, NOT claims automation.",
    "Medical Weight Management": "Digital and clinical programs for obesity and weight management. Includes GLP-1 prescription platforms and metabolic health programs.",
    "Pharma Regulatory Compliance": "Tools for pharmaceutical companies to manage FDA and international regulatory compliance. NOT clinical trial software, NOT general compliance.",
    "AI Foundation Models For Biology": "Foundation models trained on biological data (genomics, proteomics, molecular biology) for research and discovery. NOT drug discovery applications, NOT clinical tools.",
    "Computational Immune Engineering": "Computational platforms for designing and modeling immune system interactions. Used in immunotherapy and vaccine development.",
    "Regulatory Submission Automation": "Automating the preparation and submission of regulatory dossiers to health authorities. NOT general compliance tools.",
    "Clinical Trial Optimization": "Software for designing, managing, and accelerating clinical trials. Includes patient recruitment, protocol optimization, and trial management. NOT regulatory submission.",
    "AI Chronic Care Management": "AI platforms for managing patients with chronic conditions. Remote monitoring, care coordination, and patient engagement. NOT general telehealth.",
    "Health Insurance Platforms": "Technology platforms enabling health insurance operations, plan design, and benefits administration. NOT digital-native insurance products, NOT claims automation.",
    "Medical Practice Software": "Practice management and EHR software for clinical operations. Scheduling, billing, documentation. NOT specialty workflow tools.",
    "Immune System Analytics": "Tools for analyzing immune system data and responses for research and clinical applications. NOT computational immune engineering.",
    "Cancer Precision Therapeutics": "Platforms and therapies targeting cancer through genomic profiling and precision medicine. NOT diagnostics.",
    "Male Reproductive Health": "Digital health platforms for male fertility, reproductive health, and sexual wellness.",
    "Neural Interface Technologies": "Hardware and software interfaces between the nervous system and external devices. Brain-computer interfaces and neural prosthetics.",
    "AI Oncology Diagnostics": "AI systems for detecting and diagnosing cancer from imaging, pathology, and genomic data. NOT treatment planning.",
    "Medical Imaging AI": "AI for analyzing medical images across radiology, pathology, and ophthalmology. Includes detection, segmentation, and diagnostic support. NOT oncology-specific tools.",
    "Healthcare Practice Management": "Operational and administrative software for managing healthcare facilities. Scheduling, billing, staff management. NOT clinical documentation or EHR.",
    "AI Orthodontic Imaging": "AI tools for orthodontic imaging analysis and treatment planning in dental workflows.",
    "AI Ambient Clinical Assistants": "AI systems that passively listen during clinical encounters to automate documentation and note generation. NOT general voice assistants.",
    "AI Fertility Treatment Optimization": "AI platforms optimizing fertility treatments including IVF, embryo selection, and reproductive outcomes.",
    "Provider Credentialing Automation": "Automating verification and credentialing of healthcare providers specifically for payers and health systems. NOT general HR credentialing.",
    "Specialty Practice Workflow Automation": "Workflow automation built for specific medical specialties (dermatology, ophthalmology, etc.). NOT general practice management.",
    "Medical Devices & Interventional Technology": "Physical medical devices, implants, and interventional technologies for diagnosis or treatment — surgical devices, implantable hardware, catheters, valves. NOT AI-driven diagnostic software (use AI Oncology Diagnostics or Medical Imaging AI), NOT drug/therapeutic products (use Therapeutics & Drug Development).",
    "Diagnostics & Testing": "Diagnostic tests and testing platforms for detecting diseases or conditions, non-AI-driven and not specific to oncology or imaging. Includes rapid tests, point-of-care diagnostics, and lab-based assays. NOT AI Oncology Diagnostics, NOT Medical Imaging AI, NOT Advanced Microscopy Diagnostics.",
    # Life Sciences
    "AI For Market Access": "Tools helping life sciences companies navigate and optimize market access, pricing, and reimbursement strategies.",
    "AI For Material Discovery": "AI-driven platforms for discovering novel materials with targeted properties. NOT drug discovery, NOT general material science simulation.",
    "AI For Drug Discovery": "AI platforms accelerating discovery of novel drug candidates. Includes target identification, molecular design, and ADMET prediction.",
    "AI For Material Science": "AI tools for predicting and modeling material properties and behavior. NOT drug discovery.",
    "Federated AI For Life Sciences": "Federated learning infrastructure enabling collaborative AI model training across healthcare and life science data silos without sharing raw data.",
    "AI Clinical Trial Optimization": "AI-specific tools for optimizing trial design, patient stratification, and outcomes. NOT general trial management software.",
    "AI Precision Oncology Diagnostics": "AI platforms diagnosing cancer subtypes and informing treatment through multi-omic data analysis.",
    "AI Neuroscience Research": "AI tools and platforms for neuroscience research, brain mapping, and neural data analysis.",
    "AI Driven Bioproduction": "AI systems optimizing biomanufacturing and bioprocessing workflows. Includes fermentation optimization and cell culture monitoring.",
    "AI For Patent Intelligence": "AI platforms analyzing patents for R&D strategy, freedom-to-operate, and competitive intelligence in life sciences.",
    "Advanced Microscopy Diagnostics": "Diagnostic platforms leveraging advanced microscopy for pathology and cell biology applications.",
    "AI Medical Workflow": "AI tools for streamlining clinical and hospital workflows. NOT ambient documentation, NOT imaging diagnostics.",
    "AI Material Science Simulation": "Computational simulation platforms for modeling material behavior at atomic or molecular scale.",
    "Therapeutics & Drug Development": "Companies developing and clinically trialing drugs, biologics, or other therapeutic treatments through traditional (non-AI-driven) R&D. NOT AI For Drug Discovery (that's for AI-driven discovery platforms/tooling), NOT Cancer Precision Therapeutics (oncology-specific).",
    # Developer Tools & Infrastructure
    "CI/CD & DevOps": "Platforms for continuous integration, continuous delivery, and DevOps automation. Includes build pipelines, deployment automation, and infrastructure as code.",
    "Observability & Monitoring": "Tools for application performance monitoring, logging, distributed tracing, and alerting. NOT security monitoring, NOT infrastructure provisioning.",
    "Low-Code / No-Code": "Platforms enabling non-developers to build applications and automations with minimal coding. NOT horizontal workflow automation.",
    "API Infrastructure": "Platforms for building, managing, securing, and monetizing APIs. Includes API gateways, developer portals, and API lifecycle management.",
    "Search Infrastructure": "Infrastructure for building and scaling search functionality in applications. Includes vector search, full-text search, and search-as-a-service.",
    "AI Driven Developer Productivity": "STRICT DEFINITION. AI tools whose USERS are software developers and whose function is accelerating the software development workflow itself: code review automation, documentation generation, test generation, codebase understanding, and engineering project planning/analytics. The test: is the daily user a developer working on code? NOT code generation/completion, even if it also reviews code (use AI Code Generation And Repair — e.g. Cursor), NOT API or model providers that developers merely integrate (use API Infrastructure or their domain subsector), NOT MLOps, NOT general productivity tools for non-developers, NOT production monitoring/observability after deployment (use Observability & Monitoring), NOT security vulnerability scanning (use AppSec / DevSecOps), NOT general workflow/agent automation platforms (use AI Agent Platforms And Automation or Low-Code / No-Code).",
    "AI Code Generation And Repair": "AI tools that generate, complete, review, or fix code. Targets developers directly.",
    "Infrastructure Monitoring": "Platforms for monitoring health, performance, and availability of infrastructure and cloud resources. NOT application-level observability.",
    # CleanTech
    "AI Weather And Climate": "AI platforms for weather forecasting, climate modeling, and climate risk analytics. NOT energy forecasting, NOT carbon markets.",
    "Textile Waste Recycling": "Technologies and platforms for recycling textile waste and enabling circular fashion supply chains.",
    "Solar Water Purification": "Solar-powered water purification and desalination technologies for clean water access.",
    "Renewable Energy Forecasting": "AI tools for forecasting renewable energy production (solar, wind) for grid operators and asset owners.",
    "Energy Storage Systems": "Technologies for storing energy at grid scale or distributed level. Includes battery systems and alternative storage.",
    "Enzyme Based Recycling": "Biotechnology platforms using enzymes to break down and recycle materials such as plastics and textiles.",
    "Pollution Control Technology": "Technologies for capturing, reducing, or neutralizing industrial and environmental pollutants.",
    "Sustainable Metal Recovery": "Technologies for recovering metals from waste streams, electronic waste, or low-grade ores sustainably.",
    "Decarbonized Industrial Heat": "Technologies replacing fossil fuels in industrial heat processes with low-carbon alternatives (electric, hydrogen).",
    "Transport Emissions Capture": "Technologies for capturing or reducing emissions directly from transportation vehicles and fleets.",
    "Urban Heat Solutions": "Technologies addressing urban heat islands through cooling infrastructure, green design, and advanced building materials.",
    "Sustainable Biomanufacturing": "Bio-based manufacturing producing materials, chemicals, or fuels as sustainable alternatives to fossil-derived products.",
    "Circular Appliance Solutions": "Platforms and business models for extending appliance life through repair, refurbishment, and circular models.",
    "E Waste Metal Recovery": "Technologies specifically for recovering valuable metals from electronic waste.",
    "Industrial Byproduct Upcycling": "Converting industrial waste or byproducts into higher-value materials or products.",
    "Demand Response Management": "Platforms enabling utilities and businesses to manage electricity demand in response to grid and price signals.",
    "Water Efficiency Solutions": "Technologies and software for reducing water consumption and improving water management in industrial and municipal contexts.",
    "Grid Resilience Technology": "Technologies strengthening the electrical grid against failures, extreme weather, and demand volatility.",
    # EdTech
    "K-12 Education": "Digital learning platforms and tools for K-12 students and teachers. Includes curriculum, tutoring, and classroom management.",
    "Higher Education": "Software and platforms for universities and colleges. Includes LMS, student success tools, and campus administration.",
    "AI For Education And Creativity": "AI tools for personalized learning, educational content creation, and creative skill development, for schools and higher-education institutions. NOT corporate/professional training (use HRTech > Corporate Learning), NOT general AI tools used incidentally in education.",
    # E-commerce & Retail
    "D2C Brands": "Direct-to-consumer product brands selling through owned digital channels. The product IS the brand, not the infrastructure enabling brands.",
    "Refurbished Electronics Marketplace": "Marketplaces and platforms for buying and selling certified refurbished electronics.",
    "AI Powered Commerce": "AI tools enhancing online shopping through personalization, product recommendation, and discovery. NOT full e-commerce platforms.",
    "Visual Commerce Tools": "Tools enabling image-based product discovery, AR try-on, and shoppable media experiences.",
    "Restaurant Management": "Software for restaurant and commercial kitchen operations — POS, digital ordering, back-office, invoice and cost management, margin tracking, food waste monitoring, and guest engagement. Customers are restaurant owners, food service operators, and commercial kitchens. NOT food production or food science companies, NOT payment infrastructure (FinTech), NOT generic local-business booking tools.",
    "Hospitality & Travel Operations": "Software for hotel, accommodation, and travel/hospitality operators — revenue management, dynamic pricing, booking and reservation systems, channel management, and property operations. Customers are hotel owners, managers, and chains. NOT restaurant-specific operations (use Restaurant Management), NOT consumer-facing travel booking marketplaces for end travelers. A point solution focused on pricing/revenue/booking belongs here even if described as the operator's core operational system — it doesn't need to span finance/HR/procurement to qualify.",
    "Retail Commerce Automation": "Automation tools for retail back-office operations — inventory replenishment, pricing, and supply chain. NOT general e-commerce platforms.",
    "AI Commerce Integration": "Middleware and integration platforms connecting commerce systems, ERPs, and marketplaces with AI-driven automation.",
    "AI Native Ecommerce Platforms": "Full-stack e-commerce platforms built with AI at the core for storefront and merchandising. NOT AI plugins for existing platforms.",
    # Marketing Tech
    "SEO & Content": "Tools for search engine optimization, content strategy, and organic content creation and distribution — including Generative Engine Optimization (GEO): measuring, tracking, and improving a brand's visibility, citations, and representation within AI-powered search and chat platforms (ChatGPT, Claude, Perplexity, Gemini, AI Overviews). GEO is the same organic-discoverability problem as SEO, just for AI answer engines instead of traditional search results.",
    "Social Media": "Tools for managing, scheduling, and analyzing social media presence and paid social campaigns.",
    "Ad Tech": "Platforms for programmatic advertising, ad buying, audience targeting, and campaign management.",
    "Influencer Marketing": "Platforms for discovering, managing, and measuring influencer partnerships and campaigns.",
    "Brand Safety And Marketing": "Tools ensuring brand advertising appears in appropriate contexts and protecting brand reputation online.",
    "AI Lead Generation": "AI platforms identifying, scoring, and generating sales leads from first and third-party data.",
    "Outbound Sales Automation": "Tools automating outbound sales sequences across email, LinkedIn, and multi-channel prospecting. NOT CRM, NOT inbound marketing.",
    "Web Data Intelligence": "Platforms collecting and analyzing web data for competitive intelligence, pricing, and market research.",
    "Retail Intelligence": "Analytics platforms providing pricing, shelf, and competitive intelligence to consumer goods and retail companies.",
    "Consumer Insights Automation": "Platforms automating consumer research, survey analysis, and customer feedback processing at scale.",
    "Video Ad Automation": "Platforms for automated creation, personalization, and distribution of video advertising content.",
    "Automated Marketing Assets": "AI tools generating and managing marketing creatives, copy, and assets at scale.",
    "Personalized Media Experiences": "Platforms delivering individually personalized content and media experiences across channels.",
    # Quantum Computing
    "Quantum Processors & Systems": "Companies building quantum processors, QPUs, and full quantum computing systems. NOT quantum software or algorithms.",
    # Aerospace & Defense
    "Aviation And Flight Systems": "Avionics, flight management systems, and technology for manned aircraft operations and safety.",
    "AI Aerospace Defense Simulation": "AI-powered simulation and training platforms for aerospace and defense applications.",
    "Aerospace Defense": "Defense systems and technology for military aerospace operations. Broad category for defense hardware not covered by more specific tags.",
    "Drone Defense Systems": "Systems designed to detect, track, and neutralize hostile drones. Counter-UAS technology.",
    "Defense And Security Robotics": "Robotic systems built specifically for defense and security operations. NOT industrial robotics.",
    "Military And Defense Automation": "Software and automation platforms for military logistics, operations, and command systems.",
    "Aviation Operational Intelligence": "Analytics platforms for commercial aviation operations — fleet, crew, maintenance, and route optimization.",
    # Energy
    "Energy Efficiency Software": "Software helping businesses and buildings reduce energy consumption and optimize energy use.",
    "Nuclear Energy": "Companies developing nuclear power generation technologies, including advanced fission and fusion.",
    "AI Energy Infrastructure": "AI platforms managing and optimizing energy infrastructure — grids, pipelines, and generation assets.",
    "AI Industrial Operations": "AI tools optimizing industrial plant operations, production processes, and asset performance. NOT robotics, NOT general manufacturing ERP.",
    # Mobility
    "Urban Mobility Solutions": "Platforms and services enabling urban transportation — shared mobility, micro-mobility, and multimodal travel.",
    "Electric Cargo Mobility": "Electric vehicles and platforms for cargo transport and last-mile delivery logistics.",
    "EV Charging Networks": "Infrastructure, networks, and software for electric vehicle charging. Includes CPOs and charging management systems.",
    # SpaceTech
    "Space Based Energy": "Technologies for harvesting and transmitting energy from space to Earth.",
    "Dedicated Small Satellite Launch": "Launch vehicles and services dedicated to deploying small satellites and smallsat constellations.",
    "Space Based Data Services": "Data products and analytics derived from satellite imagery and space-based sensors.",
    "Mars Surface Exploration": "Technologies and missions for surface exploration of Mars. Hardware and robotics for Martian operations.",
    "Reusable Space Vehicles": "Spacecraft designed for reusability to reduce launch costs. Includes reusable rockets and crew vehicles.",
    "In Space Mobility": "Propulsion and maneuvering systems for operating and repositioning spacecraft in orbit.",
    "Launch And Propulsion Systems": "Rocket engines, propulsion technologies, and launch vehicles for reaching orbit and beyond. NOT dedicated small satellite launch.",
    # HRTech
    "HR Management Platforms": "Core HR software for managing employee records, payroll, benefits, and workforce data. NOT candidate sourcing, screening, or hiring (use Recruiting And Talent Acquisition), NOT employee training or development content (use Corporate Learning).",
    "Recruiting And Talent Acquisition": "Platforms for candidate sourcing, screening, assessment, and interview management. Includes ATS, job boards, skills-based assessments, automated video interviews, talent marketplaces, and bias reduction tools. NOT general HR management, NOT payroll, NOT workforce compliance.",
    "Workforce Compliance Platforms": "Tools ensuring compliance with labor laws, workforce regulations, and employment standards.",
    "Gig Economy Platforms": "Self-serve marketplaces and management platforms where contingent workers, freelancers, or on-demand labor are sourced, matched, or managed at scale via the platform itself. NOT managed-services or staffing providers that personally source and deploy experts for a specific client engagement without a self-serve marketplace — classify those by what they deliver instead (e.g. Corporate Learning for training/leadership program delivery).",
    "Corporate Learning": "Platforms and services delivering employee training, upskilling, leadership development, and professional development within organizations — whether self-serve software, content libraries, or expert/coach-delivered programs. NOT K-12 or higher-education institutions (use EdTech), NOT coding bootcamps for career-changers outside employment.",
    # InsurTech
    "Insurance Claims Automation": "Software automating insurance claims intake, processing, and settlement workflows.",
    "Insurance Backoffice Automation": "Automation tools for insurance carrier back-office operations — underwriting, policy administration, and data management.",
    "Wholesale Insurance Marketplace": "Digital platforms connecting wholesale insurance brokers, MGAs, and capacity providers.",
    "Climate Risk Insurance": "Insurance products and analytics tools addressing climate-related risks for property, agriculture, and infrastructure.",
    "Commercial Insurance Brokerage": "Digital brokerages and platforms for placing commercial insurance coverage for businesses.",
    "Specialty And Emerging Risk Insurance": "Insurance products and platforms covering emerging and non-standard risks not addressed by traditional policies. Includes AI liability coverage, cyber risk for autonomous systems, tech E&O, and parametric insurance products. NOT general commercial insurance brokerage, NOT claims automation.",
    # LegalTech
    "Legal Compliance Automation": "Software automating legal compliance monitoring and management for corporations. NOT regulatory document processing.",
    "AI Legal Practice Automation": "AI tools built for lawyers and law firms themselves to perform legal practice work — contract analysis, legal research, document drafting, case summarization, client intake, and legal secretarial/administrative automation. The primary user is a practicing lawyer or law firm staff, not a corporate compliance or legal-ops team. NOT compliance monitoring or regulatory tracking for in-house/corporate legal teams (use Legal Compliance Automation), NOT regulatory document processing for other industries (use Regulatory Document Automation), NOT policy/legislative intelligence (use Policy Intelligence And News).",
    "Regulatory Document Automation": "Tools automating the drafting, review, and processing of regulatory documents and filings.",
    "Audit And Risk Automation": "Platforms automating internal audit, risk assessment, and control testing workflows.",
    "AI Risk Certification": "Platforms for assessing, certifying, and documenting AI system risks for regulatory and governance purposes.",
    "Policy Intelligence And News": "Platforms tracking legislative changes, regulatory updates, and policy developments for businesses and legal teams.",
    "Product Compliance Management": "Software managing product regulatory compliance across markets — certifications, standards, and product documentation.",
    # PropTech
    "Construction Project Intelligence": "Software for monitoring, managing, and optimizing construction project performance. Includes site intelligence and project analytics. NOT general project management.",
    "AI Engineering Design": "AI tools for engineering design, structural analysis, and BIM in construction and infrastructure projects.",
    # Hardware
    "Precision Additive Manufacturing": "Advanced 3D printing systems and services for industrial and precision manufacturing applications.",
    "Consumer Electronics": "Hardware products for consumer use — smart devices, personal gadgets, and connected home products.",
    "Semiconductor & Chips": "Companies designing or manufacturing semiconductors, chips, and integrated circuits.",
    "Sensors & IoT Devices": "Hardware sensors and connected devices for data collection across industrial, consumer, and infrastructure applications.",
    # FoodTech
    "Sustainable Food Production & Ingredients": "Companies producing novel or more sustainable food ingredients, proteins, and crops — fermentation-derived proteins, alternative proteins, novel crop domestication, natural food colorants and additives, and byproduct-to-ingredient conversion. NOT consumer-facing nutrition apps or supplements (use Personalized Nutrition & Wellness), NOT food manufacturing process/quality software (use Food Manufacturing & Quality Tech), NOT companies whose primary output is raw agricultural commodities or farm-level crop cultivation without processing into a food ingredient (use AgriTech).",
    "Food Manufacturing & Quality Tech": "Software and AI platforms for food and beverage manufacturers — quality control, process automation, machine vision, and yield optimization on the production line. NOT the food product itself, NOT restaurant-facing tools (use Restaurant Management).",
    "Personalized Nutrition & Wellness": "Consumer-facing products delivering personalized nutrition, supplementation, or meal guidance — nutrition/gut-health testing and coaching apps, meal planning tools, and personalized supplement or functional-food products. NOT clinical/medical nutrition tools for diagnosed conditions (use HealthTech), NOT B2B food ingredient companies (use Sustainable Food Production & Ingredients).",
    "Food Supply Chain & Traceability": "Platforms connecting food producers with buyers and providing traceability, fair pricing, and direct trade infrastructure across the food supply chain. NOT general supply chain software outside food/agriculture (use Supply Chain & Logistics Automation), NOT farm-level crop production (use AgriTech).",
    # AgriTech
    "Farm Operations & Precision Agriculture": "Technology used directly in farm production and operations — precision sensing, remote monitoring, input optimization, machinery/labor tracking, and operational compliance for farms and cooperatives.",
    "Agricultural Finance & Commodity Markets": "Financial and market-facing platforms serving the agriculture value chain — farmer financing/lending, commodity trading and procurement, price risk hedging, and agrifood market intelligence.",
    "Agricultural Biosecurity & Wildlife Management": "Detection and management of wildlife-related risks and biosecurity threats affecting agriculture and adjacent critical infrastructure.",
    # MediaTech
    "AI Media Management": "AI platforms for managing, organizing, and distributing digital media assets at scale. DAM and content operations.",
    "Generative Media Tools": "Tools using generative AI to create images, video, and audio content. NOT general creative software.",
    "Digital Experience Development": "Platforms and tools for building and deploying digital experiences — CMS, DXP, and web experience platforms.",
    "Digital Experience Design": "Tools for designing digital user experiences — UX design, prototyping, and design systems.",
    "AI Content Production": "AI tools accelerating content production workflows — scripting, editing, post-production, and publishing automation.",
    # Consumer Tech
    "Gaming & Entertainment": "Consumer platforms and products for gaming, interactive entertainment, and immersive experiences.",
    "Personal Productivity": "Consumer tools for individual task management, organization, and personal efficiency. NOT enterprise productivity tools.",
    "Social & Community": "Platforms for social networking, community building, and peer connection. NOT enterprise collaboration.",
    "Lifestyle & Wellness": "Consumer apps and products for fitness, mindfulness, and personal wellness. NOT clinical health tools.",
    "Accessibility & Inclusion": "Technology products designed to improve digital and physical accessibility for people with disabilities.",
    # PetTech
    "Pet Insurance": "Insurance products and platforms covering veterinary care costs for pets.",
    "Veterinary Tech": "Software and tools for veterinary practice management, diagnostics, and clinical operations.",
    "Pet Nutrition & Wellness": "Products and platforms for pet nutrition, supplements, and general wellness.",
    "Pet Training & Behavior": "Digital and physical tools for pet training, behavior modification, and obedience.",
    "Pet Monitoring & Connected Devices": "Connected devices for tracking and monitoring pet health, activity, and location.",
}
