create table quality_review_log (
  id bigint generated by default as identity primary key,
  review_type text not null,
  subject text not null,
  date_diagnosed timestamptz not null default now(),
  source_snapshot jsonb,
  verdict text not null,
  resolution text,
  notes text
);

alter table quality_review_log enable row level security;
